### ISSUE TITLE
Fill bucket?

### ISSUE THREAD

**Issue by jessemillar** [sebashwa/vixl44#3]
Would be quite useful. https://en.wikipedia.org/wiki/Flood_fill

**Comment by sebashwa** [comment]
Most definitely! Already missed this feature myself.. I think I have to re-prioritize my todo list a bit. This feature will be pretty much on top of it

**Comment by sebashwa** [comment]
I'm closing this issue because flood fill is [is now possible](https://github.com/sebashwa/vixl44/commit/acee597f223564fcfe977603486856b8930ea6eb) 🙂
