### ISSUE TITLE
sixel support

### ISSUE THREAD

**Issue by stuaxo** [sebashwa/vixl44#5]
Sixel support would be nice, or would that version be vixl66 ?

**Comment by sebashwa** [comment]
This is awesome, I didn't even know this format exists 😄 Not sure whether this is in scope of vixl44 or if it should be a different tool, though. Feels more like vixl66 to me (although with this name the 'number-pun' doesn't work anymore 😞)

**Comment by stuaxo** [comment]
There is libsixel, having a seperate project is probably too much overhead

http://saitoha.github.io/libsixel/

**Comment by sebashwa** [comment]
It's really crazy what's possible with sixel! Since it is possible to export to .png now you can use
`img2sixel` to convert it to sixel format 👍
